infodir=/usr/share/info
filelist="gdbm.info"

post_install() {
 [ -x usr/local/bin/install-info ] || return 0
 for file in ${filelist}; do
    usr/bin/install-info $infodir/$file.gz $infodir/dir 2> /dev/null || return 0
 done
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  [ -x usr/local/bin/install-info ] || return 0
  for file in ${filelist}; do
    usr/bin/install-info --delete $infodir/$file.gz $infodir/dir 2> /dev/null
  done
}

post_upgrade
