infodir=compat/linux/usr/share/info
file=grep.info

post_install() {
  [ -x compat/linux/usr/bin/install-info ] || return 0
  compat/linux/usr/bin/install-info $infodir/$file.gz $infodir/dir 2> /dev/null
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  [ -x compat/linux/usr/bin/install-info ] || return 0
  compat/linux/usr/bin/install-info --delete $infodir/$file.gz $infodir/dir 2> /dev/null
}
