infodir=/compat/linux//usr/share/info
filelist=(gettext.info.gz autosprintf.info.gz)

post_install() {
  [ -x compat/linux/usr/bin/install-info ] || return 0
  for file in ${filelist[@]}; do
    install-info $infodir/$file $infodir/dir 2> /dev/null
  done
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  [ -x compat/linux/usr/bin/install-info ] || return 0
  for file in ${filelist[@]}; do
    install-info --delete $infodir/$file $infodir/dir 2> /dev/null
  done
}
