infodir=usr/share/info
filelist="gnutls.info-1.gz gnutls.info-2.gz gnutls.info-3.gz gnutls.info-4.gz gnutls.info-5.gz gnutls.info.gz gnutls-guile.info.gz"

post_install() {
  for file in ${filelist}; do
    install-info $infodir/$file $infodir/dir 2> /dev/null
  done
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  for file in ${filelist}; do
    install-info --delete $infodir/$file $infodir/dir 2> /dev/null
  done
}
