post_install() {
	getent group polkit >/dev/null || pw groupadd polkit -g 562 >/dev/null
        getent passwd polkit >/dev/null || pw useradd polkit -u 562 -g 562 -d / -s /bin/false -c polkit polkit >/dev/null
}

post_upgrade() {
	post_install
}

post_remove() {
	getent passwd polkit >/dev/null && pw userdel polkit >/dev/null
        getent group polkit >/dev/null && pw groupdel polkit >/dev/null
        true
}
