diff -rupN SGMLSpm/Makefile ../SGMLSpm/Makefile
--- SGMLSpm/Makefile	1995-12-05 14:26:11.000000000 +0200
+++ ../SGMLSpm/Makefile	2013-09-22 01:31:16.000000000 +0300
@@ -82,8 +82,6 @@ install_html: ${HTML_SOURCES}
 	cd DOC; make html
 	rm -rf ${HTMLDIR}/SGMLSpm ${HTMLDIR}/sgmlspl
 	cp -r ${HTML_SOURCES} ${HTMLDIR}
-	chmod a+x,a+r ${HTMLDIR}/SGMLSpm ${HTMLDIR}/sgmlspl
-	chmod a+r ${HTMLDIR}/SGMLSpm/* ${HTMLDIR}/sgmlspl/*
 
 docs:
 	cd DOC; make all
