post_install() {
    [ -x usr/local/bin/install-info ] || return 0
    install-info --quiet usr/share/info/nano.info.gz usr/share/info/dir
}
pre_remove() {
    [ -x usr/local/bin/install-info ] || return 0
    install-info --quiet --delete usr/share/info/nano.info.gz usr/share/info/dir
}
post_remove() {
    if [ -f usr/share/info/dir ]; then if sed -e '1,/Menu:/d' usr/share/info/dir | grep -q '^[*] '; then true; else rm usr/share/info/dir; fi; fi
}
