infodir=usr/share/info
infofile=glib.info.gz

post_install() {
  install-info --quiet $infodir/$infofile $infodir/dir
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  install-info --quiet --delete $infodir/$infofile $infodir/dir
}

post_remove() {
	if [ -f $infodir/dir ]; then 
		if sed -e '1,/Menu:/d' $infodir/dir | grep -q '^[*] '; then 
			true; 
		else 
			rm $infodir/dir;
		fi; 
	fi
}
