post_install() {
	if [ -f usr/bin/mktexlsr ]; then
		echo    ">>> texlive: updating the filename database..."
		usr/bin/mktexlsr
	fi

	if [ -f usr/bin/fmtutil-sys ]; then
		echo -n   "creating all formats..."
		usr/bin/fmtutil-sys --all 1>/dev/null
		echo      " done." 
		echo      " (logs are under /var/lib/texmf/web2c/<engine>/<formatname>.log)"
	fi
}

post_upgrade() {
	echo    ">>> texlive: updating the filename database..."
	usr/bin/mktexlsr
}
