post_install() {
	install-info --quiet /usr/share/info/gnupg.info.gz /usr/share/info/dir

}

pre_remove() {
	[ -L /usr/bin/gpg ] && rm -f /usr/bin/gpg || true
	/sbin/ldconfig -R
	install-info --quiet --delete /usr/share/info/gnupg.info.gz /usr/share/info/dir
}

post_deinstall() {
	if [ -f /usr/share/info/dir ]; 
	then 
		if sed -e '1,/Menu:/d' /usr/share/info/dir | grep -q '^[*] '; 
		then 
			true; 
		else 
			rm /usr/share/info/dir; 
		fi; 
	fi
}

