post_install() {
  echo -n "Updating font cache... "
  fc-cache -f > /dev/null
  mkfontscale usr/share/fonts/terminus-font
  mkfontdir usr/share/fonts/terminus-font
  echo "done."
  echo ">>> To enable the terminus font add"
  echo "    FontPath \"/usr/share/fonts/terminus-font\""
  echo ">>> to the \"Files\" section in your xorg.conf"
}

post_upgrade() {
  post_install
}

post_remove() {
  echo -n "Updating font cache... "
  fc-cache -f > /dev/null
}
