post_install() {
	/sbin/ldconfig -m /usr/lib
	[ -x usr/local/bin/install-info ] || return 0
	install-info --quiet usr/share/info/gpgme.info.gz usr/share/info/dir
}

pre_remove() {
	/sbin/ldconfig -R
	install-info --quiet --delete usr/share/info/gpgme.info.gz usr/share/info/dir
	if [ -f usr/share/info/dir ]; 
	then 
		if sed -e '1,/Menu:/d' usr/share/info/dir | grep -q '^[*] '; 
		then 
			true; 
		else 
			rm usr/share/info/dir; 
		fi; 
	fi
}

