post_install() {
	[ -f etc/dbus-1/system.d/org.freedesktop.PolicyKit1.conf ] || cp etc/dbus-1/system.d/org.freedesktop.PolicyKit1.conf.dist etc/dbus-1/system.d/org.freedesktop.PolicyKit1.conf
}

pre_remove() {
	if cmp -s etc/dbus-1/system.d/org.freedesktop.PolicyKit1.conf etc/dbus-1/system.d/org.freedesktop.PolicyKit1.conf.dist; then 
		rm -f etc/dbus-1/system.d/org.freedesktop.PolicyKit1.conf ; 
	fi
}

post_upgrade() {
	post_install
}
